### ISSUE TITLE
Not working on Debian distro kali with python 3 and python 2

### ISSUE THREAD

**Issue by jackhallloween21** [DH-AL/Dh-All#1]
When running ./Dh-All.sh
It is shown even with sudo and in su.
File ".x.py", line 4
SyntaxError: Non-ASCII character '\xda' in file .x.py on line 5, but no encoding declared; see http://python.org/dev/peps/pep-0263/ for details

Not working on Debian with python 3 and python 2

**Comment by naiyan-official** [comment]
This tool was make for termux based.  We Don't test it on debian  so give
us some time we will fixed this problem.

Thank you for your feedback

**Comment by naiyan-official** [comment]
try bash Dh-All.sh. 

And there are some bugs in the tool so we are trying to fixed though..  Thanks

**Comment by jackhallloween21** [comment]
I tried bash Dh-All.sh
And I think it is compatible with python 3.9 and in termux when I install python it was python 3.9 so it was working without any issues but when I checked my phython version on my Debian then it was python 3.7 I tried to update it but it showed that it is the lastest version.

**Comment by naiyan-official** [comment]
Ok, I'll check it out.
