### ISSUE TITLE
problem starting app

### ISSUE THREAD

**Issue by ans20112003** [DH-AL/Dh-All#7]
I have this problem 
![Screenshot_2023-09-18-04-01-28-972_com termux](https://github.com/DH-AL/Dh-All/assets/78283490/f82e9dc3-9151-414e-bc5d-1c7407f7c3e4)
and when I try starting using ./ 
this appears 
![Screenshot_2023-09-18-04-03-12-624_com termux](https://github.com/DH-AL/Dh-All/assets/78283490/7e44497c-1ed5-4c1b-893d-bb4e82e550d1)

**Comment by Sobhagyaprasad** [comment]
Actually I think you download old version, and another thing there is a syntax error so you can understand you type a wrong syntax and if you are using python in mobile then you must use pyroid3. If you use python in PC or computer then use the latest version for that you search python.org .

**Comment by blasbalgitay** [comment]
I'm also experiencing the same error...
downloaded the tool from here.

**Comment by clownkilla1981** [comment]
What you need to do is, expore more with the command. You will get the answer after that.

**Comment by naiyanrahman** [comment]
Hello there,
Sorry to say but this project has already been closed long time ago and i upload the source code of this project that you can check it and modify as you want thanks
