### ISSUE TITLE
$ git config --global alias.co checkout $ git config --global alias.br branch $ git config --global alias.ci commit $ git config --global alias.st status

### ISSUE THREAD

**Issue by lwfyh** [DH-AL/Dh-All#9]
https://github.com/DH-AL/Dh-All/blob/db4fb08e603bf9fb54eada94bb9c0665c3c82dbd/Dh-All.sh#L1C1-L1C1

name: Use the data

on:
  workflow_run:
    workflows: [Upload data]
    types:
      - complete
jobs:
  download:
    runs-on: ubuntu-latest
    steps:
      - name:  Download artifact 
        uses: actions/github-script@v6
        with:
          script: |
            let allArtifacts = await github.rest.actions.listWorkflowRunArtifacts({
               owner: context.repo.owner,
               repo: context.repo.repo,
               run_id: context.payload.workflow_run.id,
            });
            let matchArtifact = allArtifacts.data.artifacts.filter((artifact) => {
              return artifact.name == "pr_number"
            })[0];
            let download = await github.rest.actions.downloadArtifact({
               owner: context.repo.owner,
               repo: context.repo.repo,
               artifact_id: matchArtifact.id,
               archive_format:  zip ,
            });
            let fs = require( fs );
            fs.writeFileSync(`${process.env.GITHUB_WORKSPACE}/pr_number.zip`, Buffer.from(download.data));

      - name:  Unzip artifact 
        run: unzip pr_number.zip

      - name:  Comment on PR 
        uses: actions/github-script@v6
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            let fs = require( fs );
            let issue_number = Number(fs.readFileSync( ./pr_number ));
            await github.rest.issues.createComment({
              owner: context.repo.owner,
              repo: context.repo.repo,
              issue_number: issue_number,
              body:  Thank you for the PR! 
            });

**Comment by lwfyh** [comment]
### $ git tag
v1.0
v2.0

**Comment by lwfyh** [comment]
؍.َِ😻 َِ🌸 َِ⚡ۥَِ،!

**Comment by lwfyh** [comment]
؍.َِ🥰 َِ💖 َِ🌺ۥَِ،!

**Comment by naiyanrahman** [comment]
Hello there,
Sorry to say but this project has already been closed long time ago and i upload the source code of this project that you can check it and modify as you want thanks
